# Generated by Django 4.0.2 on 2022-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('enquiry', models.CharField(max_length=1000)),
                ('collabration', models.CharField(max_length=5)),
            ],
        ),
    ]
