# Generated by Django 4.0.2 on 2022-03-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.PositiveBigIntegerField(default=1234567890),
            preserve_default=False,
        ),
    ]
