# Generated by Django 4.0.2 on 2022-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='collabration',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
